# This is used for planning only and does not represent the final grammar.

program ::= [stmt]

stmt ::= draw_stmt
      |  cmd_stmt
      |  comment

comment ::= "//" any

draw_stmt ::= element_stmt
cmd_stmt ::= let_stmt
           | def_stmt
           | include_stmt  # TODO

let_stmt ::= "!let" identifier "=" element_stmt

def_stmt ::= "!def" identifier "=" "{" content_template "}"
content_template ::= any "$attrs$" any "$content$" any

include_stmt ::= "!include" "\"" path "\""
path ::= [A-Za-z/.]+

element_stmt ::= identifier "[" attrs "]" "{" content "}"
              |  identifier "[" attrs "]"
              |  identifier "{" content "}"
              |  identifier

content ::= any

attrs ::= css_identifier
       |  css_class
       |  css_style

css_identifier ::= "#" [A-Za-z\-_]+
css_class      ::= "." [A-Za-z\-_]+
css_style      ::= [A-Za-z\-_]+ "=" any

any ::= [A-Za-z\-_0-9%.]+
