# Decks Grammar
# This is used for planning only and does not represent the final grammar.


# PROGRAM

program ::= [stmt]


# STATEMENTS

stmt ::= draw_stmt
      |  cmd_stmt
      |  comment

draw_stmt ::= element_stmt
           |  string_literal
cmd_stmt ::= let_stmt
           | def_stmt
           | include_stmt  # TODO
comment ::= "//" content_single_line


# COMMAND STATEMENTS

let_stmt ::= "!let" identifier "=" element_stmt
def_stmt ::= "!def" identifier "=" "{" content_template "}"
include_stmt ::= "!include" "\"" path "\""

content_template ::= any "$props$" any "$content$" any
path ::= [A-Za-z/.]+


# DRAW STATEMENTS

element_stmt ::= identifier "[" props "]" "{" [stmt] "}"
              |  identifier "[" props "]"
              |  identifier "{" [stmt] "}"
              |  identifier

string_literal ::= "\"" content_single_line "\""
                |  "[[" content_multi_line "]]"

content_single_line ::= any
content_multi_line ::= any | newline

props ::= html_identifier
       |  html_class
       |  html_style
       |  html_attr

html_identifier ::= "#" [A-Za-z\-_]+
html_class      ::= "." [A-Za-z\-_]+
html_style      ::= "%" [A-Za-z\-_]+ "=" any
html_attr       ::= [A-Za-z\-_]+ "=" any


# MISC 

any ::= [A-Za-z\-_0-9%.]+
