name: decks
version: 0.1.0.0
github: "farbodsz/decks"
license: MIT
author: "Farbod Salamat-Zadeh"
copyright: "2021 Farbod Salamat-Zadeh"
synopsis: A DSL and Editor for Creating Slides
category: Text
description:
  Please see the README on GitHub at <https://github.com/farbodsz/decks#readme>

dependencies:
  - base >= 4.7 && < 5
  - optparse-applicative >= 0.16 && < 0.17
  - megaparsec >= 9.0 && < 9.1
  - text >= 1.2 && < 1.3

default-extensions:
  - OverloadedStrings
  - RecordWildCards

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  decks:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - decks
